project_name: bake

#before:
#  hooks:
#    # You may remove this if you don't use go modules.
#    - go mod download
#    # you may remove this if you don't need go generate
#    - go generate ./...

release:
  github:
#    owner: taxibeat
#    name: bake

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      #- windows
      - darwin
    main: ./cmd/bake/

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      #windows: Windows
      386: i386
      amd64: x86_64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
