## yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.jsonschema.json
version: "2"

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  modules-download-mode: vendor
  build-tags:
    - component
    - integration

output:
  print-issued-lines: true
  print-linter-name: true

linters:
  default: none
  enable:
    # analyzers / style / correctness
    - unparam
    - goconst
    - prealloc
    - unconvert
    - unused
    - staticcheck
    - ineffassign
    - gosec
    - tparallel
    - whitespace
    - revive
    - godot
    - errorlint
    - gocritic
    - errname
    - govet
    - predeclared
    - nestif
    - exhaustive
    - forcetypeassert
    - nilerr
    - errcheck
    - bodyclose
    - durationcheck
    - errchkjson
    - sloglint
    - dupword
    - noctx
    - makezero
    - nilnil
    - reassign
    - spancheck
    - testifylint
    - rowserrcheck
    - sqlclosecheck
    - goprintffuncname
    - tagalign
    - testableexamples
    - nonamedreturns
    - perfsprint
    - dogsled
    - protogetter
    - usestdlibvars
  # (fast option removed in v2; default behavior is acceptable.)

formatters:
  enable:
    - gofmt
    - goimports
    - gofumpt
  settings:
    goimports: {}

issues:
  uniq-by-line: false
  exclude-use-default: false
  max-same-issues: 0
  exclude-dirs:
    - vendor
