run:
  timeout: 5m
  tests: true
  modules-download-mode: vendor
  build-tags:
    - component
    - integration

linters:
  disable-all: true
  enable:
    - govet
    - revive
    - gofumpt
    - gosec
    - unparam
    - goconst
    - prealloc
    - stylecheck
    - unconvert
    - errcheck
    - ineffassign
    - unused
    - tparallel
    - whitespace
    - staticcheck
    - gosimple
    - gocritic

issues:
  exclude-use-default: false
  max-same-issues: 0
