name: Bake docker image creation
on:
  release:
    types: [published]
jobs:
  build:
    name: Bake docker
    runs-on: ubuntu-latest
    steps:      
      - name: Check out source code
        uses: actions/checkout@v2
      - name: Get release version
        id: get_version
        # Expect release tags to be in semver format with a 'v' prefix.
        run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:11})
      - name: Build and Publish to Dockerhub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: taxibeat/bake
          username: ${{ secrets.DOCKERHUBUSER }}
          password: ${{ secrets.DOCKERHUBPWD }}
          tags: "latest,${{ env.RELEASE_VERSION }}"
