name: Bake docker image creation
on:
  release:
    types: [published]
jobs:
  update:
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@master
      - name: Build and Publish to Dockerhub
        pre: echo ::save-state name=RELEASE_VERSION::$(echo ${GITHUB_REF:11})
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: taxibeat/bake
          username: ${{ secrets.DOCKERHUBUSER }}
          password: ${{ secrets.DOCKERHUBPWD }}
          tags: "latest,${{ env.STATE_RELEASE_VERSION }}"
