name: Bake docker image creation
on:
  release:
    types: [published]
jobs:
  build:
    name: Bake docker
    runs-on: ubuntu-latest
    steps:      
      - name: Check out source code
        uses: actions/checkout@v2
      - name: Build and Publish
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: taxibeat/bake/bake
          username: ${{ secrets.GitHubUser }}
          password: ${{ secrets.GitHubToken }}
          registry: docker.pkg.github.com
          tag_semver: true
