name: Bake docker image creation
on:
  release:
    types: [published]
jobs:
  publish:
    name: Publish docker image to registry
    runs-on: ubuntu-latest
    steps:      
      - name: Check out source code
        uses: actions/checkout@v3
      - name: Get release version
        # Expect release tags to be in semver format with a 'v' prefix.
        run: echo "RELEASE_VERSION=${GITHUB_REF:11}" >> $GITHUB_ENV
      - name: Build and Publish Image
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          registry: ghcr.io
          name: taxibeat/bake
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          tags: "latest,${{ env.RELEASE_VERSION }}"
          buildargs: GH_TOKEN=${{ secrets.MATCHING_BAKE }}
