name: Confluence Docs Sync
on:
  release:
    types: [published]
jobs:
  build:
    name: Sync Docs
    runs-on: ubuntu-latest
    steps:      
      - name: Check out source code
        uses: actions/checkout@v2

      - name: Set up Go 1.14
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: Sync
        run:  go run cmd/bake/main.go doc:confluencesync
        env:
          CONFLUENCE_USERNAME: ${{ secrets.ConfluenceUsername }}
          CONFLUENCE_PASSWORD: ${{ secrets.ConfluencePassword }}
          CONFLUENCE_BASEURL: ${{ secrets.ConfluenceBaseURL }}
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
