name: Go dependency upgrade
on:
  # schedule:
  #   - cron: 0 9 1,15 * *
  pull_request:    
jobs:
  build:
    name: Go dependency upgrade
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:          
          go-version-file: 'go.mod'      

      - name: Upgrade Go dependencies
        if: success()
        run: |
          go get -u all
          go mod tidy
          go mod vendor

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.MATCHING_BOT_GPG_SECRET }}
          passphrase: ${{ secrets.MATCHING_BOT_GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Create PR
        if: success()
        run: |
          git checkout -b go-deps-update
          git add .
          git -c user.name="Matching Bot" -c user.email="matching.engineers@thebeat.co" commit -S -m "Go dependencies update"
          git push --set-upstream origin go-deps-update
          gh pr create -t "Go dependencies" --body "Go dependencies"
        env:
          GITHUB_TOKEN: ${{ secrets.MATCHING_BAKE }}
           
      - name: Notify slack success
        if: success()
        env:
          SLACK_USERNAME: matching-ci-bot
          SLACK_WEBHOOK: ${{ secrets.MATCHING_CI_SLACK_WEBHOOK }}
          SLACK_MESSAGE: 'Success :rocket:'
          SLACK_TITLE: ${{ github.repository }} CI run
          SLACK_COLOR: good
          SLACK_FOOTER: Powered by the Matching Domain
        uses: rtCamp/action-slack-notify@v2

      - name: Notify slack fail
        if: failure()
        env:
          SLACK_USERNAME: matching-ci-bot
          SLACK_WEBHOOK: ${{ secrets.MATCHING_CI_SLACK_WEBHOOK }}
          SLACK_MESSAGE: 'Failure :facepalm1:'
          SLACK_TITLE: ${{ github.repository }} CI run
          SLACK_COLOR: danger
          SLACK_FOOTER: Powered by the Matching Domain
        uses: rtCamp/action-slack-notify@v2
