name: Mage docker image creation
on:
  push:
  schedule:
    - cron: '0 2 * * 0' # Weekly on Sundays at 02:00
jobs:
  build:
    name: Mage docker
    runs-on: ubuntu-latest
    steps:      
      - name: Check out source code
        uses: actions/checkout@v2
      - name: Build and Publish
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: taxibeat/dispatch-domain/mage
          username: ${{ secrets.GitHubUser }}
          password: ${{ secrets.GitHubToken }}
          registry: docker.pkg.github.com
          dockerfile: tools/mage/Dockerfile
          tags: "latest,0.0.6"
          cache: ${{ github.event_name != 'schedule' }}